CREATE TABLE IF NOT EXISTS kv (k TEXT PRIMARY KEY, v TEXT, expires_at INTEGER);
CREATE TABLE IF NOT EXISTS clients (client_id TEXT PRIMARY KEY, email TEXT, first_name TEXT, updated_at INTEGER);
CREATE INDEX IF NOT EXISTS clients_email ON clients(email);
CREATE TABLE IF NOT EXISTS events (id INTEGER PRIMARY KEY AUTOINCREMENT, client_id TEXT, email TEXT, type TEXT, handle TEXT, product_id TEXT, title TEXT, at INTEGER);
CREATE INDEX IF NOT EXISTS events_email ON events(email, type, at);
CREATE INDEX IF NOT EXISTS events_client ON events(client_id, at);
CREATE TABLE IF NOT EXISTS checkouts (token TEXT PRIMARY KEY, email TEXT, customer_id TEXT, first_name TEXT, url TEXT, total TEXT, items TEXT, updated_at INTEGER, completed INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY, email TEXT, customer_id TEXT, first_name TEXT, product_ids TEXT, created_at INTEGER);
CREATE INDEX IF NOT EXISTS orders_email ON orders(email, created_at);
CREATE TABLE IF NOT EXISTS subscribers (email TEXT PRIMARY KEY, customer_id TEXT, first_name TEXT, subscribed_at INTEGER);
CREATE TABLE IF NOT EXISTS sends (id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT, flow TEXT, dedupe TEXT UNIQUE, status TEXT, error TEXT, created_at INTEGER, sent_at INTEGER, priority INTEGER DEFAULT 5, payload TEXT);
CREATE INDEX IF NOT EXISTS sends_status ON sends(status, priority, created_at);
CREATE INDEX IF NOT EXISTS sends_email ON sends(email, flow, created_at);
CREATE TABLE IF NOT EXISTS suppressions (email TEXT PRIMARY KEY, reason TEXT, at INTEGER);
